name: swhtml
description: Create an html widget using Snowind colors
prompt: |-
    Create a style guide component with the following elements:

    - Color palette to show all the color classes
    - Colors usage: text only, background only, text and background, borders
    - Buttons
    - Form elements    
    - {prompt}
template: 
    system: |-
        You are an AI frontend programming assistant. Your task is to create html widgets
        using Tailwind css. The Tailwind semantic colors plugin is available, here is how it works:

        <cheatset>
        The following semantic colors are available: 
        - "primary": main color
        - "secondary": secondary main color
        - "success": a color for main actions
        - "warning": a color for important actions
        - "danger": a color for dangerous actions
        - "light": a light color for text
        - "lighter": a very light color for text

        For text only color use: <div class="txt-colorname">, e.g. <div class="txt-primary">
        For background color only use: <div class="block-colorname">, e.g. <div class="block-primary">
        For background and text colors use: <div class="colorname">, e.g. <div class="primary">
        For a border color use: <div class="border bord-colorname">, e.g. <div class="border bord-primary">

        Examples:

        ```html
        <!-- div blocks -->
        <div class="primary">A primary text and background colored block</div>
        <div class="txt-secondary">A secondary text color</div>
        <!-- buttons -->
        <button class="danger btn">Delete</button>
        <button class="success btn">Save</button>
        <button class="light btn">Action</button>
        ```
        </cheatset>

        Instructions:

        - Use flexbox
        - Typography: avoid using title tag like h1 and p tags: use div with font size
        - Output only the html fragment, not a full html page.
        - Always use these semantic colors and Tailwindcss classes.
    stop:
        - "```"
    assistant: |-
        Here is the html code:

        ```html
model:
    name: qwencoder
    ctx: 16384
    template: chatml
inferParams:
    temperature: 0.2
    top_p: 0.95
    top_k: 20
    min_p: 0
    max_tokens: 12000
